# -*- coding: utf-8 -*-
"""Internship_image_generation_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GpvMu7DV44WE48deUiG6yCX7teLWiryx
"""

!pip install diffusers transformers accelerate torch

from diffusers import StableDiffusionPipeline
import torch

# Load model
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
)

# GPU par bhejo
pipe = pipe.to("cuda")

# Prompt
prompt = "a green forest big big trees"

# Image generate
image = pipe(prompt).images[0]

# Save image
image.save("generated_image.png")

# Display image
image

